name: Build DungeonExplorer

on: 
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest  # Use Windows since .NET Framework 4.7.2 is Windows-only

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x  # Ensures .NET SDK is installed

      - name: Install .NET Framework 4.7.2 Developer Pack
        run: |
          choco install netfx-4.7.2-devpack -y  # Install required framework

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build --no-restore

      - name: Run Tests
        run: dotnet test --no-build --verbosity normal



